"""Create trained and predict models only

Revision ID: 4cf89ec0a824
Revises: 
Create Date: 2025-07-20 01:42:14.315840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf89ec0a824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trained_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.Column('tn', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.Column('fn', sa.Integer(), nullable=True),
    sa.Column('rain_precision', sa.Float(), nullable=True),
    sa.Column('rain_recall', sa.Float(), nullable=True),
    sa.Column('rain_f1_score', sa.Float(), nullable=True),
    sa.Column('no_rain_precision', sa.Float(), nullable=True),
    sa.Column('no_rain_recall', sa.Float(), nullable=True),
    sa.Column('no_rain_f1_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trained_model_id'), 'trained_model', ['id'], unique=False)
    op.create_table('predict_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_rain', sa.Boolean(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('trust', sa.Float(), nullable=True),
    sa.Column('trained_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predict_model_id'), 'predict_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predict_model_id'), table_name='predict_model')
    op.drop_table('predict_model')
    op.drop_index(op.f('ix_trained_model_id'), table_name='trained_model')
    op.drop_table('trained_model')
    # ### end Alembic commands ###
